fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.5.1'
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '1.1.2'
  symlinks:
    y10k: "#{source_dir}"
